< POST /file-system/ HTTP/1.1
< Host: 127.0.0.1:8982
< User-Agent: python-requests/2.25.1
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Content-Length: 301
< Content-Type: application/json
< 
< {"fs_type_id": 2147483648, "name": "uYdEZmQDhVShuskmaZOYsuhUcVHFmBnEMxHzderhsZQzakVZfVTryryMbcWiUuflsqmkVQDAiohkwsndFGtZSmcBkuNRdiNWyQRnKFCUaazQOTvpLutzWoacNMJogCPklhRFxwJYaaXSQAiopsyeleGDqFHIryhqCQ", "description": "XySTHRNxIcwZlPNsLvCPFPSIDYeziSZyyaLxwlobWZoSRlLSrYPwDHpOdemIPLjPZVQhtpOzYrsSwXNJmG"}
> HTTP/1.1 422 Unprocessable Entity
> Date: Fri, 16 Apr 2021 13:22:51 GMT
> Server: Apache/2.4.38 (Debian)
> X-Powered-By: PHP/8.0.3
> Cache-Control: no-cache, private
> Content-Length: 54
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json
> 
{"fs_type_id":["The selected fs type id is invalid."]}