< POST /connection/ HTTP/1.1
< Host: 127.0.0.1:8906
< User-Agent: python-requests/2.25.1
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Content-Length: 233
< Content-Type: application/json
< 
< {"cluster_id": 2147483648, "filesystem_id": 1, "name": "WQETgOSbuVbIdEZsjxfLVeeYvdlJyLWjrLJlAAvruAUuFaomRTCxycDclyTPSoNWxnpANcFUtptJqGYflQMfZaadvZlbwGhirXWgGJGNTBaefziKydddPPmaDHZANoFLcpwihRNbVJnKhgVyfROgpmqsetWYYNJPFEWyzsluMrWyLra"}
> HTTP/1.1 422 Unprocessable Entity
> Date: Mon, 12 Apr 2021 11:04:46 GMT
> Server: Apache/2.4.38 (Debian)
> X-Powered-By: PHP/8.0.3
> Cache-Control: no-cache, private
> Content-Length: 54
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json
> 
{"cluster_id":["The selected cluster id is invalid."]}