< POST /file-system/ HTTP/1.1
< Host: 127.0.0.1:8639
< User-Agent: python-requests/2.25.1
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Content-Length: 222
< Content-Type: application/json
< 
< {"fs_type_id": 100, "name": "kNaUyYWqlGioRbzzbOiwFDmUGaAxyvUxmxLYgmiPovXkGOseTxsQgHxqMLRkFzneFwACDt", "description": "gOJImPYvLpLGludMjTsAKVlDExEFfKqsdMoIsRSmiQNwOYjuelzWMqsonPnPJYcxgfuurBkzGFhZedxmdkJClFSIMmbzXyPAbrBZrk"}
> HTTP/1.1 422 Unprocessable Entity
> Date: Wed, 14 Apr 2021 11:39:14 GMT
> Server: Apache/2.4.38 (Debian)
> X-Powered-By: PHP/8.0.3
> Cache-Control: no-cache, private
> Content-Length: 54
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json
> 
{"fs_type_id":["The selected fs type id is invalid."]}